### ISSUE TITLE
Mismatch between error report and erroneous argument in prepare_input_dataframes()

### ISSUE THREAD

**Issue by risharma214** [jessegrabowski/tsdisagg#13]
https://github.com/jessegrabowski/tsdisagg/blob/13f9a25c6a0e7d352d5795efff34e12c7206d773/tsdisagg/ts_disagg.py#L224-L228

This line checks for if the argument df2 has a datetime type index, and prints the above error, but the dataframe passed as the 'df2' argument is the high frequency dataframe at the point of call of prepare_input_dataframes() (see below).

https://github.com/jessegrabowski/tsdisagg/blob/13f9a25c6a0e7d352d5795efff34e12c7206d773/tsdisagg/ts_disagg.py#L388-L390

Just a minor issue after all. Essentially, the error message in the line above should say 'high_freq_df' instead of 'low_freq_df'. (If I understand the code correctly)

**Comment by jessegrabowski** [comment]
Thanks for this -- I'll make a patch soon. PR welcome if you don't want to wait :)

**Comment by steveshaoucsb** [comment]
Also is it possible to put @risharma214 as a contributor of this package? He is my colleague on the projects that involve your packages and we both discover some of the issues in the packages previously.
