### ISSUE TITLE
Issues related to the frequency

### ISSUE THREAD

**Issue by steveshaoucsb** [jessegrabowski/tsdisagg#14]
In the function `build_conversion_matrix`, in line 58, the following code is used to obtain the frequency of the datetimeindex:
`low_freq, _high_freq = low_index.freq, high_index.freq`
When I throw in my data from reading a csv today, it causes the following error:
```
[60](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.12/site-packages/tsdisagg/ts_disagg.py:60) low_freq_period = (
---> [61](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.12/site-packages/tsdisagg/ts_disagg.py:61)     "Y" if low_freq.name.startswith("Y") or low_freq.name.startswith("BY") else "Q"
     [62](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.12/site-packages/tsdisagg/ts_disagg.py:62) )

AttributeError: 'NoneType' object has no attribute 'name'
```

I double check on my side on the frequency of the datetimeindex through both `.freq` and `.inferred_freq` method, `.freq` will return None, and `.inferred_freq` returns `QS-DEC`.

I believe using inferred_freq will be useful here in order to deal with data fed from outside source, since the frequency is not set and stored in the csv.

**Comment by steveshaoucsb** [comment]
Also, your personal website(https://jbgrabowski.com/) is showing the website certificate is not valid, leading to non-secured connection!

**Comment by jessegrabowski** [comment]
Thanks for the heads up about my website -- I need to go pay the 50 bucks for an SSL cert

The error should be fixed; the dataframe frequencies are not set after checking their validity but before going into the `create_conversion_matrix` function. I thought that was nicer than using the inferred_freq (but between you and me, I don't fully understand why pandas makes this distinction between `freq` and `inferred_freq`)

**Comment by steveshaoucsb** [comment]
`freq` is for the frequency that is manually set by users, and 'inferred_freq' is automatically produced by pandas algorithms. I guess the way the set this is that they want to leave spaces for users to set their own desired frequency for later use, even though that will lead to producing missing value in the dataframe.

**Comment by jessegrabowski** [comment]
But it will error if you try to set a `freq` that doesn't match the `inferred_freq`

**Comment by steveshaoucsb** [comment]
I didn't encounter such error. When I set freq as "MS", for example, the data will just generate extra dates that weren't available in the input and fill them as NA.
